DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS facility;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS parent;
DROP TABLE IF EXISTS child;
DROP TABLE IF EXISTS logs;

